version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_PUBLIC_URL}
      - VITE_SUPABASE_ANON_KEY=${ANON_KEY}
    command: npm run dev -- --host
    depends_on:
      - kong

  db:
    image: supabase/postgres:14.1.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: supabase/gotrue:v2.23.0
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - API_EXTERNAL_URL=${API_EXTERNAL_URL}

  studio:
    image: supabase/studio:latest
    ports:
      - "${STUDIO_PORT}:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_PUBLIC_URL}
      - STUDIO_PORT=${STUDIO_PORT}

  kong:
    image: kong:2.8.1
    ports:
      - "${KONG_HTTP_PORT}:8000"
      - "${KONG_HTTPS_PORT}:8443"
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  storage:
    image: supabase/storage-api:latest
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGRST_JWT_SECRET: ${JWT_SECRET}
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - uploads:/var/lib/storage

  rest:
    image: postgrest/postgrest:latest
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon

volumes:
  db-data:
  pgadmin-data:
  uploads:
